-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-02 18:02:22 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo ON
spool oo_schema_output.txt

-- student: 34423680
-- student name: Ian Leong Zheng Yan

DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE PORT_SCHEDULE CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     addr_id       NUMBER (2)  NOT NULL , 
     country_code  CHAR (5)  NOT NULL , 
     addr_street   VARCHAR2 (100)  NOT NULL , 
     addr_town     VARCHAR2 (50)  NOT NULL , 
     addr_postcode VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.addr_id IS 'address_id (surrogate key)' 
;

COMMENT ON COLUMN ADDRESS.country_code IS 'code of country' 
;

COMMENT ON COLUMN ADDRESS.addr_town IS '100
' 
;

COMMENT ON COLUMN ADDRESS.addr_postcode IS '10' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( addr_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT addr_sk UNIQUE ( addr_street , addr_town , addr_postcode , country_code ) ;

CREATE TABLE CABIN 
    ( 
     cabin_number           VARCHAR2 (7)  NOT NULL , 
     ship_code              VARCHAR2 (7)  NOT NULL , 
     cabin_class            VARCHAR2 (20)  NOT NULL , 
     cabin_sleepingcapacity NUMBER (2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CABIN.cabin_number IS 'number of cabins' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'SHIP unique ID' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'cabin classes' 
;

COMMENT ON COLUMN CABIN.cabin_sleepingcapacity IS 'amount of cabin available to sleep' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_number, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code CHAR (5)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'code of country' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'name of country' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id                NUMBER (2)  NOT NULL , 
     ship_code                VARCHAR2 (7)  NOT NULL , 
     cruise_name              VARCHAR2 (100)  NOT NULL , 
     cruise_cost              NUMBER (6,2)  NOT NULL , 
     cruise_description       VARCHAR2 (200)  NOT NULL , 
     cruise_departuredatetime DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise unique id' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'SHIP unique ID' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'name of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_cost IS 'cost of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_description IS 'description of cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_departuredatetime IS 'Date for departure' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     manifest_id            NUMBER (2)  NOT NULL , 
     cruise_id              NUMBER (2)  NOT NULL , 
     passenger_id           NUMBER (2)  NOT NULL , 
     cabin_number           VARCHAR2 (7)  NOT NULL , 
     ship_code              VARCHAR2 (7)  NOT NULL , 
     manifest_boarddatetime DATE 
    ) 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'cruise unique id' 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'passengers unique id' 
;

COMMENT ON COLUMN MANIFEST.cabin_number IS 'number of cabins' 
;

COMMENT ON COLUMN MANIFEST.ship_code IS 'SHIP unique ID' 
;

COMMENT ON COLUMN MANIFEST.manifest_boarddatetime IS 'Date of boarding' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( manifest_id ) ;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT manifest_id_sk UNIQUE ( passenger_id , cruise_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id  NUMBER (2)  NOT NULL , 
     oper_name    VARCHAR2 (50)  NOT NULL , 
     oper_ceoname VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'operator unique id' 
;

COMMENT ON COLUMN OPERATOR.oper_name IS 'operator name' 
;

COMMENT ON COLUMN OPERATOR.oper_ceoname IS 'The CEO names' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id     NUMBER (2)  NOT NULL , 
     guardian_id      NUMBER (2) , 
     addr_id          NUMBER (2)  NOT NULL , 
     pass_firstname   VARCHAR2 (50) , 
     pass_lastname    VARCHAR2 (50) , 
     pass_gender      CHAR (1)  NOT NULL , 
     pass_dateofbirth DATE  NOT NULL , 
     pass_phonenumber VARCHAR2 (15) 
    ) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passengers unique id' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'passengers unique id' 
;

COMMENT ON COLUMN PASSENGER.addr_id IS 'address_id (surrogate key)' 
;

COMMENT ON COLUMN PASSENGER.pass_firstname IS 'passenger first name' 
;

COMMENT ON COLUMN PASSENGER.pass_lastname IS 'passenger last name' 
;

COMMENT ON COLUMN PASSENGER.pass_gender IS 'passenger gender M or F' 
;

COMMENT ON COLUMN PASSENGER.pass_dateofbirth IS 'Date of passenger birth' 
;

COMMENT ON COLUMN PASSENGER.pass_phonenumber IS 'passenger phone number' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      VARCHAR2 (7)  NOT NULL , 
     country_code   CHAR (5)  NOT NULL , 
     port_latitude  NUMBER (8,6)  NOT NULL , 
     port_longitude NUMBER (9,6)  NOT NULL , 
     port_name      VARCHAR2 (100)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.country_code IS 'code of country' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'latitude of port' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'longitude of port' 
;

COMMENT ON COLUMN PORT.port_name IS 'name of port' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE PORT_SCHEDULE 
    ( 
     port_schedule_id NUMBER (7)  NOT NULL , 
     cruise_id        NUMBER (2)  NOT NULL , 
     port_code        VARCHAR2 (7)  NOT NULL , 
     port_datetime    DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT_SCHEDULE.port_schedule_id IS 'schedule id for port' 
;

COMMENT ON COLUMN PORT_SCHEDULE.cruise_id IS 'cruise unique id' 
;

COMMENT ON COLUMN PORT_SCHEDULE.port_datetime IS 'date time for port' 
;

ALTER TABLE PORT_SCHEDULE 
    ADD CONSTRAINT PORT_SCHEDULE_PK PRIMARY KEY ( port_schedule_id ) ;

CREATE TABLE SHIP 
    ( 
     ship_code             VARCHAR2 (7)  NOT NULL , 
     operator_id           NUMBER (2)  NOT NULL , 
     country_code          CHAR (5)  NOT NULL , 
     ship_name             VARCHAR2 (50)  NOT NULL , 
     ship_commissioneddate DATE  NOT NULL , 
     ship_tonnage          NUMBER (8,2)  NOT NULL , 
     ship_maxguestcapacity NUMBER (5)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'SHIP unique ID' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'operator unique id' 
;

COMMENT ON COLUMN SHIP.country_code IS 'code of country' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'Name of the ship' 
;

COMMENT ON COLUMN SHIP.ship_commissioneddate IS 'When the ship got commissioned' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'carrying capacity
' 
;

COMMENT ON COLUMN SHIP.ship_maxguestcapacity IS 'Maximum number of guest  that can carry' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT address_country_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger_sk FOREIGN KEY 
    ( 
     addr_id
    ) 
    REFERENCES ADDRESS 
    ( 
     addr_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cabin_manifest_fk FOREIGN KEY 
    ( 
     cabin_number,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_number,
     ship_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT country_ship_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT cruise_manifest_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE PORT_SCHEDULE 
    ADD CONSTRAINT cruise_port_scedule_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT guardian_id_fk FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT passenger_manifest_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE PORT_SCHEDULE 
    ADD CONSTRAINT port_port_schedule_fk FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

set echo OFF
spool off